Move email format test from lc-api export test
activeprospect/themis pull request #3
Opened 2024-06-14 11:22 UTC by henriquelakiap

## Description of the change

Moved the email format validation test from `leadconduit-api` (export test-legacy) to this repository. The `lc-api` export will now only include email tests related to email address ownership, as the JSON schema email format validation logic is handled here.

## Type of change
- [X] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change
- [ ] Technical Debt
- [ ] Documentation

## Related tickets

[Ticket](https://app.shortcut.com/active-prospect/story/72936/improper-validation-of-email-to-parameter-when-exporting-lead-events)

## Checklists

### Development and Testing

- [ ]  Lint rules pass locally.
- [X]  The code changed/added as part of this pull request has been covered with tests, or this PR does not alter production code.
- [X]  All tests related to the changed code pass in development, or tests are not applicable.

### Code Review

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached.
- [ ]  At least two engineers have been added as "Reviewers" on the pull request.
- [ ]  Changes have been reviewed by at least two other engineers who did not write the code.
- [ ]  This branch has been rebased off master to be current.

### Tracking 
- [ ]  Issue from Shortcut/Jira has a link to this pull request.
- [ ]  This PR has a link to the issue in Shortcut.

### QA
- [ ]  This branch has been deployed to staging and tested.

2024-06-14 13:03 UTC, josevsalina requested changes

2024-06-14 13:03 UTC, josevsalina commented on test/pattern.js
> +describe.only('Issue #3: Crashing when pattern is incorrect in ref(erenced) schema', function() {
remove this .only here

2024-06-14 13:04 UTC, henriquelakiap commented on test/pattern.js
> +describe.only('Issue #3: Crashing when pattern is incorrect in ref(erenced) schema', function() {
😨  right now

2024-06-18 15:11 UTC, josevsalina approved these changes

2024-06-18 15:20 UTC, merged